### PR TITLE
Bio, Name and Location can now be blank

### LINKED ISSUE #15: Allow some fields to be blank
Allow some fields to be blank when updating the profile

### PR DESCRIPTION
**Pull request by kevoneil**
Fixes #15 

Also gets rid of the old sqlite table

### CODE REVIEW

**Comment by kevoneil** [comment]
@tronicdata Can you take a look at this please?

**Comment by tronicdata** [comment]
Ok, I will have a look soon

**Comment by kevoneil** [comment]
Thank you! 😄

**Comment by kevoneil** [comment]
@tronicdata Merging this in, let me know what you think afterwards!

**Pull request merged**
